export const defaultThemes = {
  white: '##FFFFFF',
  background: '#FAFAFA',
  baseCard: '#F3F2F2',
  baseInput: '#EDEDED',
  baseButton: '#E6E5E5',
  baseHover: '#E6E5E5',
  baseLabel: '#8D8686',
  baseText: '#574F4D',
  baseSubtitle: '#403937',
  baseTitle: '#272221',

  purpleLight: '#EBE5F9',
  purple: '#8047F8',
  purpleDark: '#4B2995',

  yellowLigth: '#F1E9C9',
  yellow: '#DBAC2C',
  yellowDark: '#C47F17',

  'title-title-xl': '3rem',
  'title-title-l': '2rem',
  'title-title-m': '1.5rem',
  'title-title-s': '1.2rem',
  'title-title-xs': '1.125rem',
  'text-regular-l': '1.25rem',
  'text-bold-l': '1.25rem',
  'text-regular-m': '1rem',
  'text-bold-m': '1rem',
  'text-regular-s': '0.875rem',
  'text-bold-s': '0.75rem',
  'components-tag': '0.625rem',
  'components-button-g': '0.875rem',
  'components-button-s': '0.75rem',

  regular: "'Roboto'",
  title: "'Baloo 2'",
}
